lokahi_dropbox/frontend/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/success/$', views.register_success,
        name='register_success'),
    url(r'^logout/$', views.logout_page, name='logout'),

    # Temporarily handle broken links
    url(r'^upload/$', views.upload_file, name='upload_file'),
    url(r'^upload_success/$', views.upload_success, name='upload_succes'),
]

lokahi_dropbox/groups/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.groups, name='groups'),
    url(r'^create_group/$', views.create_group, name='create_group'),
    url(r'^view_groups/$', views.view_group, name='view_group'),
    url(r'^edit_group/$', views.edit_group, name='edit_group'),
    url(r'^add_members/$', views.add_members, name='add_members'),
]

lokahi_dropbox/lokahi_dropbox/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login
# from django.contrib.auth.decorators import user_passes_test
from search.views import *
from django.conf.urls.static import static
from django.conf import settings

# login_forbidden = user_passes_test(lambda u: u.is_anonymous(), '/')

# Regular website patterns
urlpatterns = [
    url(r'^$', login, name='login'),
    # If user is not login it will redirect to login page
    url(r'^accounts/login/$', login, name='login'),
    # url(r'^admin/', include(admin.site.urls)),

    # App urls
    url(r'^', include('frontend.urls'), name='home'),
    url(r'^messaging/', include('messaging.urls'), name='messaging'),
    url(r'^groups/', include('groups.urls'), name='groups'),
    url(r'^wall/', include('wall_post.urls'), name='wall'),
    url(r'^user_management/', include('site_manager.urls'), name='manager_users'),
    url(r'^reports/', include('reports.urls'), name='reports'),
    # url(r'^createReport/', createReport),
    # url(r'^viewReport/', viewReport),
    # Search views
    url(r'^home/search/$', basic_search),
    url(r'^home/advanced_search/$', advanced_search),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve static files
urlpatterns += staticfiles_urlpatterns()
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA.ROOT)

lokahi_dropbox/frontend/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from Crypto.PublicKey import RSA
#from reports.models import *
#Gonna fix,circular dependence from Reports->Groups->BaseUser->Reports

class BaseUser(models.Model):
    user = models.OneToOneField(User)
    user_role = models.CharField(max_length=30)
    RSAkey = models.CharField(max_length=10000)
    reports = models.ManyToManyField('reports.Report')

    def set_user_role(self, user_role):
        self.user_role = user_role

lokahi_dropbox/frontend/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class RegistrationForm(forms.Form):

    role_choices = (
        ("Company User", _("Company User")),
        ("Investor User", _("Investor User")),
    )
    # Keep common field attributes in a single place
    common_attrs = {'required': True,
                    'max_length': 30, 'class': 'form-control'}
    pass_attrs = {'required': True, 'max_length': 30,
                  'render_value': False, 'class': 'form-control'}
    # Form fields
    username = forms.RegexField(
        regex=r'^\w+$',
        widget=forms.TextInput(attrs=common_attrs),
        label=_("Username"),
        error_messages={
            'invalid': _("This value must contain only letters, numbers and underscores.")
        }
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs=common_attrs),
        label=_("Email address")
    )
    pass1 = forms.CharField(
        widget=forms.PasswordInput(attrs=pass_attrs),
        label=_("Password")
    )
    pass2 = forms.CharField(
        widget=forms.PasswordInput(attrs=pass_attrs),
        label=_("Password (again)")
    )
    user_role = forms.ChoiceField(choices=role_choices)

    def clean_username(self):
        try:
            user = User.objects.get(
                username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(
            _("The username already exists. Please try another one."))

    def clean(self):
        if 'pass1' in self.cleaned_data and 'pass2' in self.cleaned_data:
            if self.cleaned_data['pass1'] != self.cleaned_data['pass2']:
                raise forms.ValidationError(
                    _("The two password fields did not match."))
        return self.cleaned_data


class UploadFileForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'required': True, 'max_length': 30}),
        label=_("File Name")
    )
    file = forms.FileField(label=_("File"), allow_empty_file=True)

lokahi_dropbox/search/forms.py
import re
from django import forms
from reports.models import *
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render_to_response, render

class BasicSearchForm(forms.Form):
    search = forms.CharField(max_length=1000)

class AdvancedSearchForm(forms.Form):
    title = forms.CharField(max_length=255, required=False)
    and_title = forms.BooleanField(required=False)
    company_name = forms.CharField(max_length=255, required=False)
    and_company_name = forms.BooleanField(required=False)
    ceo = forms.CharField(max_length=255, required=False)
    and_ceo = forms.BooleanField(required=False)
    location = forms.CharField(max_length=255, required=False)
    and_location = forms.BooleanField(required=False)
    country = forms.CharField(max_length=255, required=False)
    and_country = forms.BooleanField(required=False)
    sector = forms.CharField(max_length=255, required=False)
    and_sector = forms.BooleanField(required=False)
    projects = forms.CharField(required=False)
    and_projects = forms.BooleanField(required=False)
    time_created = forms.CharField(required=False)
    and_time_created = forms.BooleanField(required=False)

lokahi_dropbox/frontend/views.py
# Create your views here.
from frontend.forms import RegistrationForm
from .models import BaseUser
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response, render
from django.http import HttpResponseRedirect
from django.template import RequestContext
from .forms import UploadFileForm
from Crypto.PublicKey import RSA


@csrf_protect
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user_role = form.cleaned_data['user_role']

            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['pass1'],
                email=form.cleaned_data['email']
            )
            base = BaseUser.objects.create(
                user=user, user_role=user_role,
                RSAkey=RSA.generate(2048).exportKey()
            )

            return HttpResponseRedirect('/register/success/')
    else:
        form = RegistrationForm()

    variables = RequestContext(request, {
        'form': form
    })

    return render_to_response(
        'registration/register.html',
        variables,
    )


def register_success(request):
    return render_to_response(
        'registration/success.html',
    )


def upload_success(request):
    return render_to_response(
        'upload_success.html',
    )


def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')


def home(request):
    base = BaseUser.objects.get(user=request.user)
    return render_to_response(
        'home.html',
        {'user': base, 'type': base.user_role},
        context_instance=RequestContext(request)
    )


@csrf_protect
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/upload_success/')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})


def handle_uploaded_file(f):
    # Gets the file extension using substrings
    file_extension = f._get_name()[-3:]
    with open('lokahi_dropbox/temp.' + file_extension, 'wb+') as destination:
        for chunks in f.chunks():
            destination.write(chunks)

lokahi_dropbox/frontend/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Django Login Application | {% block title %}{% endblock %}</title>
    <body style="background-size:cover" background="{% static 'image/back.jpg' %}" ></body>
    <style>
    .jumbotron {
      background-size: contain;
      background-color: rgba(238, 238, 238, 0.25);
    }
    </style>
    <h1><font align="center" size="6" color="black"><b>LOKAHI FINTECH <br /> <hr align="center" size="10" nonshade width="50%" color="black"> {{user.user.username }}</b></font></h1>
</head>
<body>
  <div class="jumbotron text-center">
    <div class="container" >{% include "navbar.html" %}</div>
    <style>
    .jumbotron {
      background-color: rgba(238, 238, 238, 0);
    }
    </style>
  </div>

    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</body>
</html>

lokahi_dropbox/frontend/templates/base2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Django Login Application | {% block title %}{% endblock %}</title>
    <body style="background-size:cover" background=https://static.pexels.com/photos/2324/skyline-buildings-new-york-skyscrapers.jpg></body>
    <h1><font align="center" size="6" color="black"><b>LOKAHI FINTECH <br /> <hr align="center" size="10" nonshade width="50%" color="black"> {{user.user.username }}</b></font></h1>
</head>
<body>
  <div class="jumbotron text-center">
    <div class="container" >{% include "navbar.html"%}</div>
    <style>
    .jumbotron {
      background-size: contain;
      background-color: rgba(238, 238, 238, 0.65);
    }
    </style>
  </div>

    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</body>
</html>

lokahi_dropbox/frontend/templates/base3.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Django Login Application | {% block title %}{% endblock %}</title>
    <body style="background-size:cover" background=https://static.pexels.com/photos/2324/skyline-buildings-new-york-skyscrapers.jpg></body>
    <h1><font align="center" size="8" color="black"><b>LOKAHI FINTECH<br /> <hr align="center" size="10" nonshade width="50%" color="black"> {{user.user.username }}</b></font></h1>
</head>
<body>
    <style>
    .jumbotron {
      background-size: contain;
      background-color: rgba(238, 238, 238, 0.40);
    }
    .body {
      font-size: 22px;
    }
    </style>
    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</body>
</html>

lokahi_dropbox/frontend/templates/base4.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en">
<head>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <title>Django Login Application | {% block title %}{% endblock %}</title>
    <body style="background-size:cover" background=https://static.pexels.com/photos/2324/skyline-buildings-new-york-skyscrapers.jpg></body>
    <h1><font align="center" size="8" color="black"><b>LOKAHI FINTECH<br /> <hr align="center" size="10" nonshade width="50%" color="black"> {{user.user.username }}</b></font></h1>
</head>
<body>
  <div class="jumbotron text-center">
    <div class="container">{% include "navbar.html" %}</div>
    <style>
    .jumbotron {
      background-color: rgba(238, 238, 238, 0.65);
    }
    </style>
  </div>
    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</body>
</html>

lokahi_dropbox/frontend/templates/home.html
{% extends "base.html" %}

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <title>Lokahi Home</title>
</head>
<body>
    {% block title %}Lokahi Home{% endblock %}
    {% block head %}{% endblock %}
    {% block content %}
    <div class="jumbotron text-center">
        <div class="container"  style = "width:80%">
            <form method="POST" action="search/">
                {% csrf_token %}
                <input type="text" name="search" id="id_search"
                    class="form-control" maxlength="1000" />
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default btn-group"
                        name="submit_search" value="Search">Search</button>
                </span>
            </form>
            <br />
            {% if invalid_search == True %}
                <b><font size="3" color="red">Please enter a value in the search field!</font></b>
            {% endif %}
            <br />
            <br />
            <a class="btn btn-default" href="advanced_search/">Advanced search?</a>
            <br />
            <br />
            <h1><font size="6" color="white"><b>Our Vision<b><font></h1>
            <p align="left"><font size="4" color="white">Lokahi Fintech Crowdfunding (LFC) brings together small investors and small firms needing venture capital which would otherwise be excluded from this financial market. Companies seeking venture capital need a means to disseminate information
                about their company and its potential growth and profit in a safe and secure environment. Potential investors need a means to collect, share, and distribute information about the potential investments in a similar environment. The goal
                of this website is to develop a secure system in which companies and investors can work together to share feedback and avoid asymmetric information and moral hazards.</font></p>

            <!---<h2><p>Welcome {{ user.user.username }}!!!</p></h2>
             <h2><p>You are a {{ user.user_role }}!</p></h2> -->
        </div>
    </div>
    {% endblock %}
    </style>
</body>
</html>

lokahi_dropbox/frontend/templates/navbar.html
  <div style="text-align:center" class="btn-group">
      {% if type == "Company User" %}
          <a class="btn btn-default" href="/reports/create_report/">Create a Report</a>
      {% endif %}
      {% if type == "Site Manager" %}
          <a class="btn btn-default" href="/user_management/">Manage Users</a>
      {% endif %}
      <a class="btn btn-default" href="/reports/list_report/">View reports</a>
      <a class="btn btn-default" href="/messaging/">Messaging</a>
      <a class="btn btn-default" href="/groups/">Groups</a>
      <a class="btn btn-default" href="/wall/">Public Wall</a>
      <a class = "btn btn-default" href="/home/">Home</a>
      <a class = "btn btn-default" href="/logout/">Logout</a>
  </div>

lokahi_dropbox/frontend/templates/upload.html
{% extends "base.html" %}

<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <meta charset="UTF-8">
    <title>Upload Files</title>
</head>
<body>
    {% block title %}TEST{% endblock %}
    {% block head %}TEST{% endblock %}
    {% block content %}
    <h1>Hello</h1>
    <form method = "POST" action = "" enctype="multipart/form-data">
        {% csrf_token %}{{ form.as_p }}
        <input type="submit" class = "login" value="Upload" />
    </form>
    {% endblock %}
</body>
</html>

lokahi_dropbox/frontend/templates/upload_success.html
{% extends "base.html" %}

<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <meta charset="UTF-8">
    <title>Upload Files Successful</title>
</head>
<body>
    {% block title %}hello{% endblock %}
    {% block head %}hello{% endblock %}
    {% block content %}
    <h1>WOW</h1>
    <h1>{{form.title}}</h1>
    {% endblock %}
</body>
</html>